# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qualys_cs_api
from qualys_cs_api.models.registry_details import RegistryDetails  # noqa: E501
from qualys_cs_api.rest import ApiException


class TestRegistryDetails(unittest.TestCase):
    """RegistryDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryDetails(self):
        """Test RegistryDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qualys_cs_api.models.registry_details.RegistryDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
