# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qualys_cs_api
from qualys_cs_api.api.image_api import ImageApi  # noqa: E501
from qualys_cs_api.rest import ApiException


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = qualys_cs_api.api.image_api.ImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_images_using_delete(self):
        """Test case for delete_images_using_delete

        Delete images in your account  # noqa: E501
        """
        pass

    def test_get_image_association_using_get(self):
        """Test case for get_image_association_using_get

        Show associations for an image  # noqa: E501
        """
        pass

    def test_get_image_details_using_get(self):
        """Test case for get_image_details_using_get

        Show details of an image  # noqa: E501
        """
        pass

    def test_get_image_installed_software_using_get(self):
        """Test case for get_image_installed_software_using_get

        Show software installed on an image  # noqa: E501
        """
        pass

    def test_get_image_pivot_data_with_list_using_get(self):
        """Test case for get_image_pivot_data_with_list_using_get

        Show a list of images in your account  # noqa: E501
        """
        pass

    def test_get_image_vuln_count_using_get(self):
        """Test case for get_image_vuln_count_using_get

        Show vulnerability count for an image  # noqa: E501
        """
        pass

    def test_get_image_vuln_details_using_get(self):
        """Test case for get_image_vuln_details_using_get

        Show vulnerability details for an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
