# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qualys_cs_api
from qualys_cs_api.api.registry_api import RegistryApi  # noqa: E501
from qualys_cs_api.rest import ApiException


class TestRegistryApi(unittest.TestCase):
    """RegistryApi unit test stubs"""

    def setUp(self):
        self.api = qualys_cs_api.api.registry_api.RegistryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_schedule_using_post(self):
        """Test case for cancel_schedule_using_post

        Cancel registry schedule in your account  # noqa: E501
        """
        pass

    def test_create_aws_connector_using_post(self):
        """Test case for create_aws_connector_using_post

        Create new AWS connector  # noqa: E501
        """
        pass

    def test_create_registry_using_post(self):
        """Test case for create_registry_using_post

        Create a new registry  # noqa: E501
        """
        pass

    def test_create_schedule_using_post(self):
        """Test case for create_schedule_using_post

        Create a new registry scan schedule  # noqa: E501
        """
        pass

    def test_delete_registries_using_delete(self):
        """Test case for delete_registries_using_delete

        Delete multiple registries in your account  # noqa: E501
        """
        pass

    def test_delete_registry_using_delete(self):
        """Test case for delete_registry_using_delete

        Delete registry in your account  # noqa: E501
        """
        pass

    def test_delete_schedule_using_delete(self):
        """Test case for delete_schedule_using_delete

        Delete registry schedule in your account  # noqa: E501
        """
        pass

    def test_delete_schedules_using_delete(self):
        """Test case for delete_schedules_using_delete

        Delete multiple registry schedules in your account  # noqa: E501
        """
        pass

    def test_get_aws_base_using_get(self):
        """Test case for get_aws_base_using_get

        Fetch AWS account ID and External ID for your account  # noqa: E501
        """
        pass

    def test_get_aws_connectors_list_using_get(self):
        """Test case for get_aws_connectors_list_using_get

        Show a list of AWS connectors in your account  # noqa: E501
        """
        pass

    def test_get_aws_connectors_via_customer_account_id_using_get(self):
        """Test case for get_aws_connectors_via_customer_account_id_using_get

        Show a list of AWS connectors for an AWS account ID  # noqa: E501
        """
        pass

    def test_get_registry_details_using_get(self):
        """Test case for get_registry_details_using_get

        Show details of a registry  # noqa: E501
        """
        pass

    def test_get_registry_pivot_data_with_list_using_get(self):
        """Test case for get_registry_pivot_data_with_list_using_get

        Show a list of registries in your account  # noqa: E501
        """
        pass

    def test_get_registry_repo_pivot_list_using_get(self):
        """Test case for get_registry_repo_pivot_list_using_get

        Show a list of repositories in a registry  # noqa: E501
        """
        pass

    def test_get_schedule_pivot_list_using_get(self):
        """Test case for get_schedule_pivot_list_using_get

        Show a list of schedules created for a registry  # noqa: E501
        """
        pass

    def test_update_registry_using_put(self):
        """Test case for update_registry_using_put

        Update existing registry in your account  # noqa: E501
        """
        pass

    def test_update_schedule_using_put(self):
        """Test case for update_schedule_using_put

        Update existing registry schedule in your account  # noqa: E501
        """
        pass

    def test_validate_registry_using_post(self):
        """Test case for validate_registry_using_post

        Validate information for new registry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
