# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qualys_cs_api
from qualys_cs_api.api.sensor_api import SensorApi  # noqa: E501
from qualys_cs_api.rest import ApiException


class TestSensorApi(unittest.TestCase):
    """SensorApi unit test stubs"""

    def setUp(self):
        self.api = qualys_cs_api.api.sensor_api.SensorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sensors_using_delete(self):
        """Test case for delete_sensors_using_delete

        Delete sensors in your account  # noqa: E501
        """
        pass

    def test_get_sensor_details_using_get(self):
        """Test case for get_sensor_details_using_get

        Show details of a sensor  # noqa: E501
        """
        pass

    def test_get_sensors_list_using_get(self):
        """Test case for get_sensors_list_using_get

        Show a list of sensors in your account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
