# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "qualys-cs-api"
VERSION = "1.6.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Container Security APIs",
    author="info@qualys.com",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Container Security APIs"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    All features of the Container Security are available through REST APIs.&lt;br/&gt;Access support information at www.qualys.com/support/&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Permissions:&lt;/b&gt;&lt;br/&gt;User must have the Container module enabled&lt;br/&gt;User must have API ACCESS permission  # noqa: E501
    """
)
