# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from qualys_cs_api.configuration import Configuration


class Cvss3Info(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'base_score': 'str',
        'temporal_score': 'str'
    }

    attribute_map = {
        'base_score': 'baseScore',
        'temporal_score': 'temporalScore'
    }

    def __init__(self, base_score=None, temporal_score=None, local_vars_configuration=None):  # noqa: E501
        """Cvss3Info - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._base_score = None
        self._temporal_score = None
        self.discriminator = None

        if base_score is not None:
            self.base_score = base_score
        if temporal_score is not None:
            self.temporal_score = temporal_score

    @property
    def base_score(self):
        """Gets the base_score of this Cvss3Info.  # noqa: E501


        :return: The base_score of this Cvss3Info.  # noqa: E501
        :rtype: str
        """
        return self._base_score

    @base_score.setter
    def base_score(self, base_score):
        """Sets the base_score of this Cvss3Info.


        :param base_score: The base_score of this Cvss3Info.  # noqa: E501
        :type: str
        """

        self._base_score = base_score

    @property
    def temporal_score(self):
        """Gets the temporal_score of this Cvss3Info.  # noqa: E501


        :return: The temporal_score of this Cvss3Info.  # noqa: E501
        :rtype: str
        """
        return self._temporal_score

    @temporal_score.setter
    def temporal_score(self, temporal_score):
        """Sets the temporal_score of this Cvss3Info.


        :param temporal_score: The temporal_score of this Cvss3Info.  # noqa: E501
        :type: str
        """

        self._temporal_score = temporal_score

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cvss3Info):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Cvss3Info):
            return True

        return self.to_dict() != other.to_dict()
