# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from qualys_cs_api.configuration import Configuration


class Drift(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'category': 'list[str]',
        'reason': 'list[str]',
        'software': 'list[DriftSoftware]',
        'vulnerability': 'list[DriftVulnerability]'
    }

    attribute_map = {
        'category': 'category',
        'reason': 'reason',
        'software': 'software',
        'vulnerability': 'vulnerability'
    }

    def __init__(self, category=None, reason=None, software=None, vulnerability=None, local_vars_configuration=None):  # noqa: E501
        """Drift - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._category = None
        self._reason = None
        self._software = None
        self._vulnerability = None
        self.discriminator = None

        if category is not None:
            self.category = category
        if reason is not None:
            self.reason = reason
        if software is not None:
            self.software = software
        if vulnerability is not None:
            self.vulnerability = vulnerability

    @property
    def category(self):
        """Gets the category of this Drift.  # noqa: E501


        :return: The category of this Drift.  # noqa: E501
        :rtype: list[str]
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Drift.


        :param category: The category of this Drift.  # noqa: E501
        :type: list[str]
        """

        self._category = category

    @property
    def reason(self):
        """Gets the reason of this Drift.  # noqa: E501


        :return: The reason of this Drift.  # noqa: E501
        :rtype: list[str]
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this Drift.


        :param reason: The reason of this Drift.  # noqa: E501
        :type: list[str]
        """

        self._reason = reason

    @property
    def software(self):
        """Gets the software of this Drift.  # noqa: E501


        :return: The software of this Drift.  # noqa: E501
        :rtype: list[DriftSoftware]
        """
        return self._software

    @software.setter
    def software(self, software):
        """Sets the software of this Drift.


        :param software: The software of this Drift.  # noqa: E501
        :type: list[DriftSoftware]
        """

        self._software = software

    @property
    def vulnerability(self):
        """Gets the vulnerability of this Drift.  # noqa: E501


        :return: The vulnerability of this Drift.  # noqa: E501
        :rtype: list[DriftVulnerability]
        """
        return self._vulnerability

    @vulnerability.setter
    def vulnerability(self, vulnerability):
        """Sets the vulnerability of this Drift.


        :param vulnerability: The vulnerability of this Drift.  # noqa: E501
        :type: list[DriftVulnerability]
        """

        self._vulnerability = vulnerability

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Drift):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Drift):
            return True

        return self.to_dict() != other.to_dict()
