# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from qualys_cs_api.configuration import Configuration


class RegistryRepoResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'repo_name': 'str',
        'total_images': 'int',
        'total_scanned_images': 'int',
        'total_vulnerable_images': 'int'
    }

    attribute_map = {
        'repo_name': 'repoName',
        'total_images': 'totalImages',
        'total_scanned_images': 'totalScannedImages',
        'total_vulnerable_images': 'totalVulnerableImages'
    }

    def __init__(self, repo_name=None, total_images=None, total_scanned_images=None, total_vulnerable_images=None, local_vars_configuration=None):  # noqa: E501
        """RegistryRepoResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._repo_name = None
        self._total_images = None
        self._total_scanned_images = None
        self._total_vulnerable_images = None
        self.discriminator = None

        if repo_name is not None:
            self.repo_name = repo_name
        if total_images is not None:
            self.total_images = total_images
        if total_scanned_images is not None:
            self.total_scanned_images = total_scanned_images
        if total_vulnerable_images is not None:
            self.total_vulnerable_images = total_vulnerable_images

    @property
    def repo_name(self):
        """Gets the repo_name of this RegistryRepoResponse.  # noqa: E501


        :return: The repo_name of this RegistryRepoResponse.  # noqa: E501
        :rtype: str
        """
        return self._repo_name

    @repo_name.setter
    def repo_name(self, repo_name):
        """Sets the repo_name of this RegistryRepoResponse.


        :param repo_name: The repo_name of this RegistryRepoResponse.  # noqa: E501
        :type: str
        """

        self._repo_name = repo_name

    @property
    def total_images(self):
        """Gets the total_images of this RegistryRepoResponse.  # noqa: E501


        :return: The total_images of this RegistryRepoResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_images

    @total_images.setter
    def total_images(self, total_images):
        """Sets the total_images of this RegistryRepoResponse.


        :param total_images: The total_images of this RegistryRepoResponse.  # noqa: E501
        :type: int
        """

        self._total_images = total_images

    @property
    def total_scanned_images(self):
        """Gets the total_scanned_images of this RegistryRepoResponse.  # noqa: E501


        :return: The total_scanned_images of this RegistryRepoResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_scanned_images

    @total_scanned_images.setter
    def total_scanned_images(self, total_scanned_images):
        """Sets the total_scanned_images of this RegistryRepoResponse.


        :param total_scanned_images: The total_scanned_images of this RegistryRepoResponse.  # noqa: E501
        :type: int
        """

        self._total_scanned_images = total_scanned_images

    @property
    def total_vulnerable_images(self):
        """Gets the total_vulnerable_images of this RegistryRepoResponse.  # noqa: E501


        :return: The total_vulnerable_images of this RegistryRepoResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_vulnerable_images

    @total_vulnerable_images.setter
    def total_vulnerable_images(self, total_vulnerable_images):
        """Sets the total_vulnerable_images of this RegistryRepoResponse.


        :param total_vulnerable_images: The total_vulnerable_images of this RegistryRepoResponse.  # noqa: E501
        :type: int
        """

        self._total_vulnerable_images = total_vulnerable_images

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistryRepoResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RegistryRepoResponse):
            return True

        return self.to_dict() != other.to_dict()
