# coding: utf-8

"""
    Container Security APIs

    All features of the Container Security are available through REST APIs.<br/>Access support information at www.qualys.com/support/<br/><br/><b>Permissions:</b><br/>User must have the Container module enabled<br/>User must have API ACCESS permission  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from qualys_cs_api.configuration import Configuration


class RegistryDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aws': 'AWSDTO',
        'connectors': 'list[AWSConnector]',
        'created': 'str',
        'credential': 'CredentialDTO',
        'docker_hub_org': 'str',
        'last_scanned': 'str',
        'provider_type': 'str',
        'registry_type': 'str',
        'registry_uri': 'str',
        'registry_uuid': 'str',
        'repo_count': 'int',
        'schedule_status_list': 'dict(str, int)',
        'total_images': 'int',
        'total_scanned_images': 'int',
        'total_vulnerable_images': 'int',
        'updated': 'str'
    }

    attribute_map = {
        'aws': 'aws',
        'connectors': 'connectors',
        'created': 'created',
        'credential': 'credential',
        'docker_hub_org': 'dockerHubOrg',
        'last_scanned': 'lastScanned',
        'provider_type': 'providerType',
        'registry_type': 'registryType',
        'registry_uri': 'registryUri',
        'registry_uuid': 'registryUuid',
        'repo_count': 'repoCount',
        'schedule_status_list': 'scheduleStatusList',
        'total_images': 'totalImages',
        'total_scanned_images': 'totalScannedImages',
        'total_vulnerable_images': 'totalVulnerableImages',
        'updated': 'updated'
    }

    def __init__(self, aws=None, connectors=None, created=None, credential=None, docker_hub_org=None, last_scanned=None, provider_type=None, registry_type=None, registry_uri=None, registry_uuid=None, repo_count=None, schedule_status_list=None, total_images=None, total_scanned_images=None, total_vulnerable_images=None, updated=None, local_vars_configuration=None):  # noqa: E501
        """RegistryDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._aws = None
        self._connectors = None
        self._created = None
        self._credential = None
        self._docker_hub_org = None
        self._last_scanned = None
        self._provider_type = None
        self._registry_type = None
        self._registry_uri = None
        self._registry_uuid = None
        self._repo_count = None
        self._schedule_status_list = None
        self._total_images = None
        self._total_scanned_images = None
        self._total_vulnerable_images = None
        self._updated = None
        self.discriminator = None

        if aws is not None:
            self.aws = aws
        if connectors is not None:
            self.connectors = connectors
        if created is not None:
            self.created = created
        if credential is not None:
            self.credential = credential
        if docker_hub_org is not None:
            self.docker_hub_org = docker_hub_org
        if last_scanned is not None:
            self.last_scanned = last_scanned
        if provider_type is not None:
            self.provider_type = provider_type
        if registry_type is not None:
            self.registry_type = registry_type
        if registry_uri is not None:
            self.registry_uri = registry_uri
        if registry_uuid is not None:
            self.registry_uuid = registry_uuid
        if repo_count is not None:
            self.repo_count = repo_count
        if schedule_status_list is not None:
            self.schedule_status_list = schedule_status_list
        if total_images is not None:
            self.total_images = total_images
        if total_scanned_images is not None:
            self.total_scanned_images = total_scanned_images
        if total_vulnerable_images is not None:
            self.total_vulnerable_images = total_vulnerable_images
        if updated is not None:
            self.updated = updated

    @property
    def aws(self):
        """Gets the aws of this RegistryDetails.  # noqa: E501


        :return: The aws of this RegistryDetails.  # noqa: E501
        :rtype: AWSDTO
        """
        return self._aws

    @aws.setter
    def aws(self, aws):
        """Sets the aws of this RegistryDetails.


        :param aws: The aws of this RegistryDetails.  # noqa: E501
        :type: AWSDTO
        """

        self._aws = aws

    @property
    def connectors(self):
        """Gets the connectors of this RegistryDetails.  # noqa: E501


        :return: The connectors of this RegistryDetails.  # noqa: E501
        :rtype: list[AWSConnector]
        """
        return self._connectors

    @connectors.setter
    def connectors(self, connectors):
        """Sets the connectors of this RegistryDetails.


        :param connectors: The connectors of this RegistryDetails.  # noqa: E501
        :type: list[AWSConnector]
        """

        self._connectors = connectors

    @property
    def created(self):
        """Gets the created of this RegistryDetails.  # noqa: E501


        :return: The created of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this RegistryDetails.


        :param created: The created of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def credential(self):
        """Gets the credential of this RegistryDetails.  # noqa: E501


        :return: The credential of this RegistryDetails.  # noqa: E501
        :rtype: CredentialDTO
        """
        return self._credential

    @credential.setter
    def credential(self, credential):
        """Sets the credential of this RegistryDetails.


        :param credential: The credential of this RegistryDetails.  # noqa: E501
        :type: CredentialDTO
        """

        self._credential = credential

    @property
    def docker_hub_org(self):
        """Gets the docker_hub_org of this RegistryDetails.  # noqa: E501


        :return: The docker_hub_org of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._docker_hub_org

    @docker_hub_org.setter
    def docker_hub_org(self, docker_hub_org):
        """Sets the docker_hub_org of this RegistryDetails.


        :param docker_hub_org: The docker_hub_org of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._docker_hub_org = docker_hub_org

    @property
    def last_scanned(self):
        """Gets the last_scanned of this RegistryDetails.  # noqa: E501


        :return: The last_scanned of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._last_scanned

    @last_scanned.setter
    def last_scanned(self, last_scanned):
        """Sets the last_scanned of this RegistryDetails.


        :param last_scanned: The last_scanned of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._last_scanned = last_scanned

    @property
    def provider_type(self):
        """Gets the provider_type of this RegistryDetails.  # noqa: E501


        :return: The provider_type of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._provider_type

    @provider_type.setter
    def provider_type(self, provider_type):
        """Sets the provider_type of this RegistryDetails.


        :param provider_type: The provider_type of this RegistryDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["DockerHub", "AWS"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and provider_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `provider_type` ({0}), must be one of {1}"  # noqa: E501
                .format(provider_type, allowed_values)
            )

        self._provider_type = provider_type

    @property
    def registry_type(self):
        """Gets the registry_type of this RegistryDetails.  # noqa: E501


        :return: The registry_type of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._registry_type

    @registry_type.setter
    def registry_type(self, registry_type):
        """Sets the registry_type of this RegistryDetails.


        :param registry_type: The registry_type of this RegistryDetails.  # noqa: E501
        :type: str
        """
        allowed_values = ["V2_PRIVATE", "V2", "DockerHub", "AWS", "Azure"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and registry_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `registry_type` ({0}), must be one of {1}"  # noqa: E501
                .format(registry_type, allowed_values)
            )

        self._registry_type = registry_type

    @property
    def registry_uri(self):
        """Gets the registry_uri of this RegistryDetails.  # noqa: E501


        :return: The registry_uri of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._registry_uri

    @registry_uri.setter
    def registry_uri(self, registry_uri):
        """Sets the registry_uri of this RegistryDetails.


        :param registry_uri: The registry_uri of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._registry_uri = registry_uri

    @property
    def registry_uuid(self):
        """Gets the registry_uuid of this RegistryDetails.  # noqa: E501


        :return: The registry_uuid of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._registry_uuid

    @registry_uuid.setter
    def registry_uuid(self, registry_uuid):
        """Sets the registry_uuid of this RegistryDetails.


        :param registry_uuid: The registry_uuid of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._registry_uuid = registry_uuid

    @property
    def repo_count(self):
        """Gets the repo_count of this RegistryDetails.  # noqa: E501


        :return: The repo_count of this RegistryDetails.  # noqa: E501
        :rtype: int
        """
        return self._repo_count

    @repo_count.setter
    def repo_count(self, repo_count):
        """Sets the repo_count of this RegistryDetails.


        :param repo_count: The repo_count of this RegistryDetails.  # noqa: E501
        :type: int
        """

        self._repo_count = repo_count

    @property
    def schedule_status_list(self):
        """Gets the schedule_status_list of this RegistryDetails.  # noqa: E501


        :return: The schedule_status_list of this RegistryDetails.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._schedule_status_list

    @schedule_status_list.setter
    def schedule_status_list(self, schedule_status_list):
        """Sets the schedule_status_list of this RegistryDetails.


        :param schedule_status_list: The schedule_status_list of this RegistryDetails.  # noqa: E501
        :type: dict(str, int)
        """

        self._schedule_status_list = schedule_status_list

    @property
    def total_images(self):
        """Gets the total_images of this RegistryDetails.  # noqa: E501


        :return: The total_images of this RegistryDetails.  # noqa: E501
        :rtype: int
        """
        return self._total_images

    @total_images.setter
    def total_images(self, total_images):
        """Sets the total_images of this RegistryDetails.


        :param total_images: The total_images of this RegistryDetails.  # noqa: E501
        :type: int
        """

        self._total_images = total_images

    @property
    def total_scanned_images(self):
        """Gets the total_scanned_images of this RegistryDetails.  # noqa: E501


        :return: The total_scanned_images of this RegistryDetails.  # noqa: E501
        :rtype: int
        """
        return self._total_scanned_images

    @total_scanned_images.setter
    def total_scanned_images(self, total_scanned_images):
        """Sets the total_scanned_images of this RegistryDetails.


        :param total_scanned_images: The total_scanned_images of this RegistryDetails.  # noqa: E501
        :type: int
        """

        self._total_scanned_images = total_scanned_images

    @property
    def total_vulnerable_images(self):
        """Gets the total_vulnerable_images of this RegistryDetails.  # noqa: E501


        :return: The total_vulnerable_images of this RegistryDetails.  # noqa: E501
        :rtype: int
        """
        return self._total_vulnerable_images

    @total_vulnerable_images.setter
    def total_vulnerable_images(self, total_vulnerable_images):
        """Sets the total_vulnerable_images of this RegistryDetails.


        :param total_vulnerable_images: The total_vulnerable_images of this RegistryDetails.  # noqa: E501
        :type: int
        """

        self._total_vulnerable_images = total_vulnerable_images

    @property
    def updated(self):
        """Gets the updated of this RegistryDetails.  # noqa: E501


        :return: The updated of this RegistryDetails.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this RegistryDetails.


        :param updated: The updated of this RegistryDetails.  # noqa: E501
        :type: str
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistryDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RegistryDetails):
            return True

        return self.to_dict() != other.to_dict()
